### ISSUE TITLE
Describe how to do initial setup in docs

### ISSUE THREAD

**Issue by GregMefford** [nerves-project/nerves_network#10]
Reported by Tommy Fisher on Slack.

It turns out `Nerves.Network.setup` isn’t meant to be supervised like `Nerves.Networking` was.
Since it returns an `:ok` tuple, its supervisor won't restart it, however, the `SystemRegistry` removed its info when the process died (since it was a transient `Task`).

Update the docs with a usage example so people know not to run it as a transient supervised `Task`.

**Comment by tokafish** [comment]
Thanks for adding the issue, @GregMefford, this sums it up. I'm happy to contribute a PR for the docs - however, I'm not clear on what the right suggested approach should be. I'm just calling setup in my firmware application's `start`, which seems reasonable to me, but is there something better?

**Comment by type1fool** [comment]
Please consider adding a step about adding nerves_network to deps. It's obvious in hindsight, but newbs will appreciate the coddling.

**Comment by tokafish** [comment]
I've taken a stab at improving the docs - with an eye to:

1) Make sure users don't forget about adding to deps/applications
2) Give an example of how you might call modprobe (asked on Slack)
3) Warn that `setup` should not be called in a process that terminates (as was the case for previous nerves networking libs)

Happy to add more if desired!
