### ISSUE TITLE
What USB WiFi adapters does this work with?

### ISSUE THREAD

**Issue by LTheGreats** [nerves-project/nerves_network#12]
What USB WiFi adapters does this work with? Does it work with all of them?

**Comment by fhunleth** [comment]
There shouldn't be anything adapter-specific in `nerves_network`. The usual issue is that the Nerves system that you're using doesn't have the kernel driver for the adapter. The solution is to make a custom kernel with the driver, but I'd check the Nerves system's repo that you're using to see if it has yours. We've supported a bunch in the past, but now that boards are more frequently coming with built-in WiFi we've mostly stopped enabling support for USB WiFi adapters.

**Comment by LTheGreats** [comment]
Okay!
