### ISSUE TITLE
Handle strings for the :key_mgmt option

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_network#17]
One of the most common typos reported on the slack channel is typing the following:

`key_mgmt: "WPA-PSK"`

instead of:

`key_mgmt: :"WPA-PSK"`

It seems like this could easily be fixed by making the key_mgmt be a string rather than an atom. To avoid breaking old code, we should still support atoms.

**Comment by ConnorRigby** [comment]
This is fixed now. See [this comment](https://github.com/nerves-project/nerves_network/issues/41#issuecomment-370915628) for potential api breaking issues on later versions.
