### ISSUE TITLE
Add example for how to listen for network updates

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_network#19]
While this is technically a `system_registry` thing, It feels really helpful to anyone using the library. Here's an example:

https://github.com/fhunleth/nerves_init_gadget/blob/v0.1.0/lib/nerves_init_zero/network_manager.ex#L16
https://github.com/fhunleth/nerves_init_gadget/blob/v0.1.0/lib/nerves_init_zero/network_manager.ex#L20-L29

**Comment by ConnorRigby** [comment]
[here](https://hexdocs.pm/nerves_network/0.3.7-rc0/handling-network-updates.html#content) are some docs
