### ISSUE TITLE
Add documentation for system registry keys

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_network#21]
This is for all of the config and state keys involved with networking. I suspect that it's best to include keys provided by `nerves_network_interface` and `nerves_wpa_supplicant` for completeness since it will be annoying to jump around projects for the total picture. However, I'm open to other thoughts on handling this.

**Comment by ConnorRigby** [comment]
[this doc](https://hexdocs.pm/nerves_network/0.3.7-rc0/handling-network-updates.html#content) has links to [this](https://hexdocs.pm/nerves_network_interface/Nerves.NetworkInterface.Worker.html#t:status/0) with all the system registry keys.
