### ISSUE TITLE
If two SSIDs are configured, no reconnect when one goes down

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_network#24]
To reproduce this, setup two access points with different SSIDs. Set them both up with `Nerves.Network.setup/2`. Wait for one to connect. It doesn't matter which one, but verify the connection. Then turn off the access point that connected. The expectation is that `Nerves.Network` will associate with the second access point and everything will work fine. This doesn't happen.

**Comment by ConnorRigby** [comment]
This is a `wpa_supplicant` feature isn't it? Can't you just tell `wpa_supplicant` you want a list of networks to be tried via their api, and it handles it?

**Comment by fhunleth** [comment]
This issue is due to my misunderstanding of the return value from `setup/2`. I had thought that you could configure two SSIDs, but you can't. That would be a good feature.

Regarding `wpa_supplicant` handling this, I'm pretty sure that it could do that. `nerves_network` will still need to watch for association events so that it would know to clear IP addresses and redo DHCP.

I'm going to close this and when we get support for multiple SSIDs (not a huge priority to me yet) we can revisit.
