### ISSUE TITLE
Nerves.Network.teardown/1 return value is confusing

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_network#25]
If you have two or more SSIDs configured on the same interface, `teardown/1` just removes one configuration. It should remove all of them. The logic is that if you're calling `teardown/1` then you want to reset the interface to a clean state. I think that anyone wanting to be picky about just tearing down one SSID will want to interface with SystemRegistry directly or if this becomes a common operation, then we really need to add a `teardown/2` that lets you specify an index to remove.

**Comment by fhunleth** [comment]
I'm misunderstanding the return value. It's returning the old value. I think that it should just return `:ok` if the SystemRegistry calls succeed.

**Comment by fhunleth** [comment]
Updated the title to reflect the comment above.

**Comment by ConnorRigby** [comment]
https://hexdocs.pm/nerves_network/0.3.7-rc0/Nerves.Network.html#teardown/1 now will return `:ok`, a different bug still exists, where `teardown/1` doesn't really do anything.
