### ISSUE TITLE
`setup` API is too loose

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_network#41]
in ref to #17, #38 and by extension #40 i would like to start an official discussion of the `setup` api.

I don't personally want to support both string and atom keys for things. And this is only one part of this particular issue. I would like to parse and confirm them before passing further down to be messed up anywhere. I think the `parse_settings` function @Hermanverschooten introduced is on the right track, but instead of coxing things into a proper shape, we should enforce the proper shape. I think the public api should raise ArgumentError's when options are not inputted correctly.

**Comment by Hermanverschooten** [comment]
I agree with your sentiment.  As far as the String to Atom goes, currently the underlying WpaSupplicant requires an Atom. I know there is a pull request there too, to allow strings to be used. My idea is we should implement our strategy concerning the config, and massage it to confirm with the called APIs. That will also allow us to enforce our contract, and make it more clear to the users.

**Comment by ConnorRigby** [comment]
in 3.x releases, we are now logging an incompatible type for ifnames such as [here](https://github.com/nerves-project/nerves_network/blob/6a9bb7dab326e58d78edcb20f5afca40769dd4c3/lib/nerves_network/if_supervisor.ex#L19)

Next `major` version update, we will be actually enforcing incompatible types.

**Comment by ConnorRigby** [comment]
as of 0.3.7, you will receive warnings on incompatible settings. later versions will officially deprecate old apis
