### ISSUE TITLE
IPv4 Link-local implementation doesn't detect IP address collisions

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_network#42]
The current IPv4 implementation selects a randomly generated IP address and proceeds to use it without probing for its existence of announcing itself. See https://tools.ietf.org/html/rfc3927#section-2.2.1 for what it should be doing.

**Comment by ConnorRigby** [comment]
Closing this issue because it is a duplicate of https://github.com/nerves-project/nerves_network/issues/16
