### ISSUE TITLE
Empty settings in config.exs make any subsequent setup calls ineffective

### ISSUE THREAD

**Issue by metelik** [nerves-project/nerves_network#49]
When having provided my app with the following config.exs entry:
config :nerves_network, :default,
  eth0: [
  ]

The subsequent call to Nerves.Network.setup "eth0", ipv4_address_method: :dhcp did not seem to have any effect apart from returned :ok status. I would have to dive deeper into the root-cause so far this is the last minute discovery and do not have more data.

**Comment by ConnorRigby** [comment]
@metelik so you think calling `setup/2` should override what is in the application environment/config?

**Comment by ConnorRigby** [comment]
I found the root of this bug:
https://github.com/nerves-project/nerves_network/blob/master/lib/nerves_network/config.ex#L60

fix coming up
