### ISSUE TITLE
auto detection of wired network interface does not work when inserted after booting a device

### ISSUE THREAD

**Issue by jpandey0613** [nerves-project/nerves_network#52]
If I boot my device without wired connection and plug the ethernet cable later, the device does not detect the wired network interface until I reboot it.

**Comment by fhunleth** [comment]
Could you provide an example that reproduces this issue on one of the officially supported Nerves platforms?

**Comment by ConnorRigby** [comment]
@jpandey0613 Are you still having this issue? Did you ever come up with an example for this? closing for now due to inactivity, but feel free to open again if you still have this issue.
