### ISSUE TITLE
`0.3.7-rc0` does not work with `wlan0`, only `eth0`

### ISSUE THREAD

**Issue by pdgonzalez872** [nerves-project/nerves_network#73]
Hi!

Following up on https://github.com/nerves-project/nerves_examples/pull/85#issue-186513505 here as it pertains to this repo.

`0.3.7-rc0` seems to work correctly with `eth0` but not with `wlan0`. The fix to have it work was to use `0.3`. I tested with (rpi3) and `0.3.6` works correctly, so it stopped working in the current `.7-rc0`.

cc: @deanchouinard, @ConnorRigby

**Comment by ConnorRigby** [comment]
Good to know. I hit a couple regressions with this version that i'm going to be taking a look at this week.
