### ISSUE TITLE
Static IP in a WEP network

### ISSUE THREAD

**Issue by alde103** [nerves-project/nerves_network#90]
### Environment

* Elixir version (`elixir -v`): 1.7.2
* Nerves environment: (`mix nerves.env --info`)
Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: nil

  Pkg:         nerves_system_br
  Vsn:         1.5.2
  Type:        system_platform
  BuildRunner: nil

  Pkg:         nerves_system_rpi3
  Vsn:         1.5.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}
target:     rpi3
  toolchain:  /.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.1.0
### Current behavior
Hello everyone, i use this configuration (in config.exs):

`config :nerves_network, :default,
  wlan0: [
    ssid: System.get_env("SSID")
    ipv4_address_method: :static,
    ipv4_address: "192.168.1.20",
    ipv4_subnet_mask: "255.255.255.0",
    ipv4_gateway: "192.168.1.1",
    key_mgmt: :NONE,
    wep_key0: :"3132333435",
    wep_tx_keyidx: 0
  ]`

### Expected behavior
i expect to connect to a wep network with the disired IP but it connects to the network with another IP.

**Comment by ConnorRigby** [comment]
I think this should now be fixed on `master`. Would you mind trying it out?

**Comment by ConnorRigby** [comment]
Should be fixed in #97
